server:
  port: 8001
spring:
  application:
    name: myService1
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2   #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 5  #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
  client:
    service-url:
      defaultZone: http://118.24.241.25:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: INFO